Diary {#Diary}
==

---

## 2023 {.unnumbered #diary-2023}

### Oktober {.unnumbered #oktober-2023}

Mi 04. _Paraddidle Johnnie_, accents on open Hi-Hat, Bars 1-24. **30 min**

### September {.unnumbered #september-2023}

Mi 27. _The Breakbeat Bible, E4: Two 16th Notes in a Row on the Kick_, Beats, ex 1-12 with routine as follows. Continue with Ride Cymbal when using the Hi-Hat Pedal. A = eight notes, B = quarter notes, C = off-beat. **30 min**

$$Beat*8 \xrightarrow[ ]{to}\frac{Beat}{HH\ pedal\ ostinato\ (ABC)}*4 \xrightarrow[ ]{to}\frac{Two\ Bar\ Break\ (Main\ Groove + Beat)}{HH\ pedal\ ostinato\ (CBA)}*4 \xrightarrow[ ]{to} Beat*4$$


Mo 25. _Accents and Rebounds_, Accented Eights, ex 15 on pad and orchestrated on Drums + Impro.

Do 14. _Escritura_, instalé el Plugin [ABC_ImpExp](https://blechtrottel.net/en/abc_impex.html) para Musescore. Hay algunos parámetros que pueden omitirse al transformar un ritmo a notación ABC, aquí una pequeña tabla. 

| to remove                             | to change                                            | 
| ------------------------------------- | ---------------------------------------------------- |
| T: Title (?)                          | M: 4/4 -> M: C                                       |
| L:1/4                                 | V:1 perc nm="string" -> V:1 perc nm="string" style=x |
| K:none (after voices)                 | V:2 perc -> V:2 perc style=normal                    |
| I:percmap A A 43 normal (all similar) | adjust voices (rhythm)                               |


Mi 13. _The Breakbeat Bible, E5: Open Hi-Hat Notes_, Eight Bar Phrase.

Fr 08. _Little Sister, Queens Of The Stone Age_, transcription with Maschine + Musescore.

Do 07. _Escritura_, creé el archivo **musescore-midiExport.mxprj** para transcribir canciones fácilmente usando Maschine y Musescore. Primero ejecuto el ritmo en Maschine o utilizo el secuenciador de pasos, después exporto y guardo el beat en MIDI. En Musescore importo el archivo MIDI, luego ingreso al menú _Ver > Mezclador_ y cambio los canales a _Set de percusión_. Por último selecciono el pentagrama que incluye el Bombo y la Tarola e intercambio las voces 1 a 2 usando el menú _Herramientas_, para copiar y pegar encima las notas de Hi-Hat. Todo esto se logra fácilmente trasponiendo en Maschine: Bombo (-24), Tarola (-20), Hi-Hat Cerrado (-18),  Tom Piso (-19), Tom Bajo (-15), Tom Medio (-13), Tom Alto (-12); otros platillos dejé sin mapear.

### August {.unnumbered #august-2023}

Di 15.  _Drum Techniques of Led Zeppelin_, Black Dog, first lecture and Fill on Bar 32 practice.

Mi 09. _Paradiddle Johnnie_, Bars 1-24, Snare + accents on Jam Block.

Di 08. Little impro on _The Breakbeat Bible, Breakbeat Transcriptions: Classic Breaks, Amen Brother_ @ 137 BPM. _Transcript_, from Rueben Spyker Reel.

### Juli {.unnumbered #juli-2023}

Fr 28. _Instrumentos_ Vendí mi atril de Hi-Hat, tenía el Gajate para tocar con clave, pero extraño mi pedal. He puesto otra configuración con el pedal FD-8 y un CY-5 que tenía guardados, por ahora me gusta.

Do 20. _Rede_, hablando con mi padre, le contaba que, aunque hoy día existen muchos tutoriales para aprender a tocar ciertos ritmos y/o técnicas, aún falta describir con mayor atención los detalles, tales como postura, inclinación del tambor, alturas, tensión, peso, logitud de los dedos y brazos, flexibilidad. Esto ya se lo había comentado antes, pero no recuerdo cuando, por eso es importante este diario.

Sa 15. _Konzert_, recital de Leipzig. Todo resultó en orden y puntual. La batería fue amplificada con un micrófono de lápiz como overhead y un micrófono dinámico al bombo, Moongel en tarola, cobijas en bombo. Llegué media hora tarde, ensamblé la batería en 20 minutos con reacomodos.

Mo 11. _The Art of Bop Drumming_, Comp Example 2, lick 9 with tumbao, inverted doubles and clave. 

So 09. _The Breakbeat Bible_, Funky Drummer @ 80-84, 6-8 Minute reps. 

Sa 08. _Paradiddle Johnnie_, review till Bar 32, practice pad. 

Mi 05. _Gedanken_, ¿Cómo nos acercamos a una canción?: Instrumentación, Pulso, Ritmo, Estructura, Interpretación. 

### Juni {.unnumbered #juni-2023}

Mo 26. _The Art of Bop Drumming_, Comp Example 2, licks 5 & 6, playing triplets as 16th notes in groups of inverted doubles `e &` and placing 8ths on the last 16th `a`. Steady _tumbao_ on bass drum.

::: {#jun262023}
:::

Di 20. _The Art of Bop Drumming_, some excercises over Rumba Clave. 

So 18. _Concert_, Vi a Horacio "El Negro" Hernández en Jazzatlán. El timbalero tocó desde mi perspectiva en momentos muy fuerte y con frases forzadas. 

Do 15. _Can't Take My Eyes Off You_, transcription till chorus. 

Sa 17. _Paradiddle Johnnie_, Bars 1-24 on practice pad, @ 70 BPM. 

Di 13. _Coding_, practice of Jungle beats with Tidalcycles for the upcoming Algorave event. 

Do 08. _Paradiddle Johnnie_, Bars 1-16, shuffle feel, various orchestrations (toms, hi-hat, snare).

So 04. _The Breakbeat Bible, E6: Syncopated Accents on the Snare_, ex 1-4 with inverted doubles. _Improv_.  **40 min**

Fr 02. _Paradiddle Johnnie_, Bars 1-16, shuffle feel, accents reinforced on Bassdrum, sticks and brushes. 

### Mai {.unnumbered #mai-2023}

Mo 29. _The All American Drummer_, Solo 14 @ 50 and 60 BPM. _Take Me Out, Franz Ferdinand_, weiter bearbeitet, decided to use ligatures for open Hi-Hats as it is more explicit and _+_ markings can't be placed over silences.

Do 25. _The Breakbeat Bible, E6 Syncopated Accents on the Snare_, Beats 1-13 on lap.  

So 21. _Drum Techniques of Led Zeppelin_, Stairway to Heaven, Bar 50 @ 60 BPM, then lecture till Bar 50 @ 88 BPM. _Drumathics_ publication of _Gunga Din, The Libertines_. _Drumlogs_, website update, chapter 2, Express rhythm.

Do 18. _Drum Techniques of Led Zeppelin_, Stairway to Heaven, Bar 50 @ 60, 65, 70, 75, 80, 85, 90 BPM. `s*3 e y s*3 . 2 e s*3 a . 3 s*3 y a . 4 s ta y s ta`.

Mo 15. _The Breakbeat Bible, E3 Two 16th Notes in a Row on the Snare: 8-Bar Phrase_, one Bar, two Bars and four Bar combinations within the same structure @ 98 BPM.  **30 min** Also Bar 2 & 5 with Swing Pattern @ 98 BPM. **5 min**

Sa 13. _The Breakbeat Bible_, _E1_ Single 16th Note Subdivisions in the Snare: Beats (p.11), _E2_ Single 16th-Note Subdivisions on the Kick: Beats (p.18), _E3_ Two 16th Notes in a Row in the Snare: Beats (p.34), _E4_ Two 16th Notes in a Row on the Kick: Beats (p.43). **30 min**

Sa 06. _Don't Speak, No Doubt_, _This Love, Maroon 5_, active listening, main grooves. 

Fr 05. _Inverted Doubles_, bassdrum displacements (#e, e+, +a, a#) over doubles on Hi-Hat and Snare (cross-stick). **15 min**. Compromise on structure, constant mechanics. 

Do 04. _Drum Techniques of Led Zeppelin_, Stairway to Heaven, first verse lecture without metronome. 

Di 01. _Linear Jazz Drumming_, Cymbal Pattern 7, ex 1-8 as lecture, 4 repetitions per phrase. 

### April {.unnumbered #april-2023}

Apr 18. _Percufest 2023_, clinics from Joel Enriquez, Rick Latham, Elohim Corona; versatility, time feel (balance), gear decisions. 

Apr 17. _Rudiments_, Paradiddle (x4) + Double Paradiddle (x4) + Triple Paradiddle (x4) + Double Paradiddle (x4) + Paradiddle (x4, end on 4th beat and begin again with this hand); taken from _Aquiles Priester @ Percufest 2023_.

### März {.unnumbered #maerz-2023}

Mär 25. _4 Way Coordination_, page 5, ex 1, AB, CD, AC, BD, AD, BC, practice pads.

Mär 14. _200 Paradiddle Exercises For Drums, Pt. 1 Single Paradiddle_, Single Flammed Mill, ex 44, stroke pattern: Down, Tap, Up, Tap. **15 min**.  _Drum Techniques of Led Zeppelin_, Good Times Bad Times, Bars 1-16, Stairway To Heaven. 

Mär 13. _200 Paradiddle Exercises For Drums, Pt. 1 Single Paradiddle_, ex 1-42. **60 min**. 

Mär 10. _Linear Drum Fills. Sixteenth-Note Lessons_, Lesson 5, ex 1-9, orchestrated followed by groove improvisation, various stickings (alternate, paradiddle, doubles). 

Mär 01. _The All American Drummer_, Solo 9. _Paradidles_, hand to hand on snare drum with bassdrum displacements on beat, off-beat, eights, 1& + 2, 2& + 1.

### Februar {.unnumbered #februar-2023}

Feb 28. _Linear Drum Fills. Sixteenth-Note Lessons_, Lesson 4, ex 1-9, orchestrated followed by groove improvisation, counting out loud (# e + a) slow.

Feb 24. _Linear Drum Fills. Sixteenth-Note Lessons_, Lesson 2 & 3, ex 1-9, snare and kick followed by groove improvisation, counting out loud (# e + a) slow. **30 min**. 

Feb 22. _Linear Drum Fills. Sixteenth-Note Lessons_, Lesson 1, ex 1-9 orchestrated followed by groove improvisation, fast and slow tempos.

Feb 21. _Bass Drum Control_, Two Bar Excercises, p. 25, ex 3. Right hand on ride, left on snare, also orchestrating on toms. _The All American Drummer_, Solo 9, transitions study.

Feb 20. _Bass Drum Control_, Two Bar Excercises, p. 25, ex 2. Right hand on ride, left on snare, also orchestrating on toms.

Feb 16. _Bass Drum Control_, Two Bar Excercises, p. 25, ex 1. Right hand on ride, left on snare.

Feb 05. _Writting_, Samba exercise based on randomness to explore 16th note displacement.

Feb 04. _The All American Drummer_, Solo 9, first read.

Feb 02. _The All American Drummer_, Solo 8, practice and video recording (Instagram Story).


### Januar {.unnumbered #januar-2023}

Jan 30. _Drumathics_, publication of the transcript video from _Here Comes The Sun, The Beatles_.

Jan 06. _Drumathics_, publication of YouTube Channel.

Jan 03. _The Art of Bop Drumming_, Comp Example 2, ex 19, 20, 21 & 22 with Bembé Ostinato. _Drumathics_, Speechless transcript publication.

Jan 02. _The Art of Bop Drumming_, Comp Example 2, ex 17 & 18 with Bembé Ostinato. Funk impro. Three limb phrasing impro. 

Jan 01. _The Art of Bop Drumming_, Comp Example 2, ex 15 & 16 + 13 & 14 with Bembé Ostinato. 

## 2022 {.unnumbered #diary-2022}

### Dezember {.unnumbered #dezember-2022}

Dez 30. _The Art of Bop Drumming_, Comp Example 2, ex 13 & 14 with Bembé Ostinato. 

Dez 30. _The Art of Bop Drumming_, Comp Example 2, ex 9, 10, 11 & 12 with Bembé Ostinato. 

Dez 29. _The Art of Bop Drumming_, Comp Example 2, ex 7 & 8 with Bembé Ostinato. 

Dez 26. _The Art of Bop Drumming_, Comp Example 2, ex 5 & 6 with Bembé Ostinato. _Linear Jazz Drumming: Part One_, Cymbal Pattern 6, ex. 7 & 8. 

Dez 25. _The Art of Bop Drumming_, Comp Example 2, ex 3 & 4 with Bembé Ostinato.

Dez 24. _The Art of Bop Drumming_, Comp Example 2, ex 1 & 2 with Bembé Ostinato.

Dez 20. _The All American Drummer_, Solo 7, Bar 6 & 7, BPM 80-90, Hi-Hat off-beat. 

Dez 19. _The All American Drummer_, Solo 7, Hi-Hat off-beat, accents with Bassdrum. 

Dez 14. _Love, Zoé_, transcripción hasta puente. 

Dez 01. _Kick it: A Social History of the Drum Kit_, Noisy women, immigrant culturas and Tin Pan Alley. 
 >How do you dismiss piano music? Describe it using adjectives normally reserved for drumming. Matt Brennan. 

### November {.unnumbered #november-2022}

Nov 30. _Linear Jazz Drumming: Part One_, Cymbal Pattern 6, ex. 1-6, two Bar combinations.

Nov 25. _Iron Man, Black Sabbath_, Transcripción hasta segundo coro, _Speechless, Helmet_, Transcripción completa. _Linear Jazz Drumming: Part One_, Cymbal Pattern 5, ex 3-8.

Mi 16. _Territorial Pissings, Nirvana_, transcripción.

Di 15. _Juego de serpientes_, invención. L@s alumn@s colorean los anillos de una serpiente según la carta que han tomado aleatoriamente, en la que un ritmo está escrito.

Mo 14. _Iron Man, Black Sabbath_, Transcripción hasta Breakdown. _Linear Jazz Drumming: Part One_, Cymbal Pattern 4, ex. 5.

Sa 12. _Speechless, Helmet_, Transcripción hasta minuto 1:32. _Linear Jazz Drumming: Part One_, Cymbal Pattern 4, ex. 1,2 3, 4.

Fr 11. _California Dreamin', The Mamas & The Papas_, Transcripción.

Do 10. _Linear Jazz Drumming: Part One_, Cymbal Pattern 3, ex. 6, 7 & 8 with various orchestrations ideas. Most studied: ex. 7 `x ~ ta . 2 x ta`

Mi 09. _Linear Jazz Drumming: Part One_, Cymbal Pattern 1, 2 & 3.

Do 03. _Impro_ Comping mit yesterdays Idea. 

Di 02. _Jazz fill idea_ `~ ~ s . k k s . s k s . hh ~ ~`

### Oktober {.unnumbered #oktober-2022}

Do 26. _Accents and Rebounds_, Accented Eighths, ex 15. **15 min**. 

Mi 25. _Gamba, gamba!_, transcripción de MIDI a código en Haskell (TidalCycles), _Territorial Pissings, Nirvana_, active listening.

Mo 24. _Kick it: A Social History of the Drum Kit_, Instruments of a lower order. _Conversación_ Reusability of drums, de la no casualidad del reggaetón.  

So 23. Recogimos mi batería para traerla junto con el resto de los instrumentos al estudio. Es ist noch nicht komplett aufgeräumt. 

Sa 22. FTS en Línea 2. Tocamos en dos segmentos interrumpidos por una muy corta lluvia. Algunos ya se iban cuando empezamos a tocar y nuestra música más los visuales de Esteban los hicieron quedarse. 

Fr 21. Band rehearsal, stomachache. 

Mo 17. _Jon Beavis: War, Never Fight A Man With A Perm_. Which cymbals?, when this or that? Tom orchestrations + Singing.

Sa 15. _Rudiments_, Paradiddle + Paraparadidle, 2 Bars exercise (2 groups of 16th notes + 2 groups of 16th note triplets + 1 group after another), 60-68 (increments by 2 every 3 minutes), 5 min rest, 70-80 BPM (increments by 2 every 2 minutes). Band rehearsal.

::: {#okt152022}
:::

Fr 14. _Rudiments_, Paradiddle + Paraparadidle, 1 Bar exercise (2 groups of 16th notes + 2 groups of 16th note triplets), 80 BPM & 60 BPM, Hi-Hat on quarters and eights. **15 min**.

Do 13. _Semillero EP, Dengue Dengue Dengue_, improvisación sobre piezas con escobillas. **17 min**.

Mi 12. _Alfabeto, Gepe_, should I use a 5-stroke roll or will a drag suffice? // Denkst du, dass uns komplizierte Sachen gefallen? Ja, klar! Wir suchen nur Probleme.

Di 11. _Advanced Techniques for the Modern Drummer, Section I Part B Eights_, ex 1-3; ex 4-7 (100-120 BPM); ex 4 w/Rumba Ostinato (100-120 BPM), right hand quarter notes + left hand orchestration. _16th note bass drum groove improvisation_, left hand 16ths + accents on beats 2 & 4, right hand 8ths. **2h 30min**. 

::: {#okt112022}
:::

---
